version: 1
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    filename: "logs/app.log"
    formatter: default
    level: INFO

  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO

loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: False

  uvicorn.error:
    handlers: [console, file]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: False

root:
  handlers: [console, file]
  level: INFO
